# ~~ Generated by projen. To modify, edit .projenrc.js and run "npx projen".
FROM jsii/superchain:1-buster-slim-node14
RUN npm install -g projen
RUN echo 'alias pj="npx projen"' >> /home/gitpod/.bashrc
RUN npm install -g cdk